-- ============================================================================
-- FugaPET_HML - H7 - PROPOSTA DE INCREMENTAL PARA O GAIA DADOS
-- NAO EXECUTAR SEM REVISAO E APROVACAO.
-- Alvo: fuga_jales_local_homologacao_v1_2 / schema homologacao.
--
-- O baseline V1.1 ja contem este modelo. Este arquivo formaliza o incremental
-- separado e bloqueia a execucao quando qualquer tabela H7 ja existir.
-- ============================================================================

BEGIN;
SET LOCAL search_path TO homologacao, public;

DO $$
DECLARE
    v_existentes text[];
BEGIN
    SELECT array_agg(table_name ORDER BY table_name)
      INTO v_existentes
      FROM information_schema.tables
     WHERE table_schema = 'homologacao'
       AND table_name IN (
           'entrada_produto_lancamento',
           'entrada_produto_item',
           'entrada_produto_pesagem'
       );

    IF COALESCE(array_length(v_existentes, 1), 0) > 0 THEN
        RAISE EXCEPTION
            'H7 nao aplicado: objetos ja existentes: %.',
            array_to_string(v_existentes, ', ');
    END IF;

    IF to_regprocedure('homologacao.fn_definir_atualizado_em()') IS NULL
       OR to_regprocedure(
           'homologacao.fn_registrar_log_alteracao_cadastral()'
       ) IS NULL THEN
        RAISE EXCEPTION 'Funcoes genericas de auditoria nao encontradas.';
    END IF;
END $$;

CREATE TABLE homologacao.entrada_produto_lancamento (
    codigo_entrada_produto_lancamento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido text NOT NULL,
    fornecedor text,
    codigo_sap_pedido_compra bigint
        REFERENCES homologacao.sap_pedido_compra(codigo_sap_pedido_compra)
        ON DELETE SET NULL,
    codigo_setor bigint
        REFERENCES homologacao.setor(codigo_setor) ON DELETE RESTRICT,
    terminal text,
    codigo_usuario bigint NOT NULL
        REFERENCES homologacao.usuario(codigo_usuario) ON DELETE RESTRICT,
    status_lancamento varchar(30) NOT NULL DEFAULT 'ABERTO',
    iniciado_em timestamptz NOT NULL DEFAULT now(),
    finalizado_em timestamptz,
    observacao text,
    situacao_entrada_produto_lancamento boolean NOT NULL DEFAULT true,
    entrada_produto_lancamento_criado_por bigint NOT NULL
        REFERENCES homologacao.usuario(codigo_usuario) ON DELETE RESTRICT,
    entrada_produto_lancamento_criado_em timestamptz NOT NULL DEFAULT now(),
    entrada_produto_lancamento_atualizado_por bigint
        REFERENCES homologacao.usuario(codigo_usuario) ON DELETE RESTRICT,
    entrada_produto_lancamento_atualizado_em timestamptz,
    CONSTRAINT ck_entrada_lancamento_numero
        CHECK (length(trim(numero_pedido)) > 0),
    CONSTRAINT ck_entrada_lancamento_status
        CHECK (status_lancamento IN (
            'ABERTO', 'EM_PESAGEM', 'FINALIZADO_LOCAL', 'ENVIADO_SAP',
            'CONFIRMADO_SAP', 'ERRO_SAP', 'CANCELADO'
        )),
    CONSTRAINT ck_entrada_lancamento_periodo
        CHECK (finalizado_em IS NULL OR finalizado_em >= iniciado_em),
    CONSTRAINT ck_entrada_lancamento_finalizado
        CHECK (
            status_lancamento NOT IN (
                'FINALIZADO_LOCAL', 'ENVIADO_SAP', 'CONFIRMADO_SAP'
            )
            OR finalizado_em IS NOT NULL
        )
);

COMMENT ON TABLE homologacao.entrada_produto_lancamento IS
    'Lancamento historico. Permite varias entradas para o mesmo pedido.';

CREATE INDEX ix_entrada_lancamento_pedido
    ON homologacao.entrada_produto_lancamento (numero_pedido)
    WHERE situacao_entrada_produto_lancamento = true;
CREATE INDEX ix_entrada_lancamento_status
    ON homologacao.entrada_produto_lancamento (
        status_lancamento, iniciado_em DESC
    )
    WHERE situacao_entrada_produto_lancamento = true;

CREATE TABLE homologacao.entrada_produto_item (
    codigo_entrada_produto_item bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_entrada_produto_lancamento bigint NOT NULL
        REFERENCES homologacao.entrada_produto_lancamento(
            codigo_entrada_produto_lancamento
        ) ON DELETE RESTRICT,
    codigo_sap_pedido_compra_item bigint
        REFERENCES homologacao.sap_pedido_compra_item(
            codigo_sap_pedido_compra_item
        ) ON DELETE SET NULL,
    numero_item text NOT NULL,
    material text,
    centro text,
    deposito text,
    unidade text,
    quantidade_prevista numeric(14,3),
    quantidade_recebida numeric(14,3),
    status_item varchar(30) NOT NULL DEFAULT 'ABERTO',
    situacao_entrada_produto_item boolean NOT NULL DEFAULT true,
    entrada_produto_item_criado_por bigint NOT NULL
        REFERENCES homologacao.usuario(codigo_usuario) ON DELETE RESTRICT,
    entrada_produto_item_criado_em timestamptz NOT NULL DEFAULT now(),
    entrada_produto_item_atualizado_por bigint
        REFERENCES homologacao.usuario(codigo_usuario) ON DELETE RESTRICT,
    entrada_produto_item_atualizado_em timestamptz,
    CONSTRAINT ck_entrada_item_numero
        CHECK (length(trim(numero_item)) > 0),
    CONSTRAINT ck_entrada_item_qtd_prevista
        CHECK (quantidade_prevista IS NULL OR quantidade_prevista >= 0),
    CONSTRAINT ck_entrada_item_qtd_recebida
        CHECK (quantidade_recebida IS NULL OR quantidade_recebida >= 0),
    CONSTRAINT ck_entrada_item_status
        CHECK (status_item IN (
            'ABERTO', 'EM_PESAGEM', 'FINALIZADO_LOCAL', 'ENVIADO_SAP',
            'CONFIRMADO_SAP', 'ERRO_SAP', 'CANCELADO'
        ))
);

COMMENT ON TABLE homologacao.entrada_produto_item IS
    'Item do lancamento. O item SAP pode se repetir em lancamentos diferentes.';

CREATE UNIQUE INDEX uq_entrada_item_lancamento_numero
    ON homologacao.entrada_produto_item (
        codigo_entrada_produto_lancamento, numero_item
    )
    WHERE situacao_entrada_produto_item = true;
CREATE INDEX ix_entrada_item_sap
    ON homologacao.entrada_produto_item (codigo_sap_pedido_compra_item)
    WHERE situacao_entrada_produto_item = true;

CREATE TABLE homologacao.entrada_produto_pesagem (
    codigo_entrada_produto_pesagem bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_entrada_produto_item bigint NOT NULL
        REFERENCES homologacao.entrada_produto_item(
            codigo_entrada_produto_item
        ) ON DELETE RESTRICT,
    sequencia integer NOT NULL,
    peso_bruto_kg numeric(14,3) NOT NULL,
    peso_tara_kg numeric(14,3) NOT NULL DEFAULT 0,
    peso_liquido_kg numeric(14,3) NOT NULL,
    codigo_tara bigint
        REFERENCES homologacao.tara(codigo_tara) ON DELETE SET NULL,
    codigo_balanca bigint
        REFERENCES homologacao.balanca(codigo_balanca) ON DELETE SET NULL,
    origem varchar(10) NOT NULL DEFAULT 'BALANCA',
    status_pesagem varchar(30) NOT NULL DEFAULT 'VALIDA',
    leitura_original text,
    payload_balanca jsonb,
    codigo_usuario bigint NOT NULL
        REFERENCES homologacao.usuario(codigo_usuario) ON DELETE RESTRICT,
    pesado_em timestamptz NOT NULL DEFAULT now(),
    situacao_entrada_produto_pesagem boolean NOT NULL DEFAULT true,
    entrada_produto_pesagem_criado_por bigint NOT NULL
        REFERENCES homologacao.usuario(codigo_usuario) ON DELETE RESTRICT,
    entrada_produto_pesagem_criado_em timestamptz NOT NULL DEFAULT now(),
    entrada_produto_pesagem_atualizado_por bigint
        REFERENCES homologacao.usuario(codigo_usuario) ON DELETE RESTRICT,
    entrada_produto_pesagem_atualizado_em timestamptz,
    CONSTRAINT ck_entrada_pesagem_sequencia CHECK (sequencia > 0),
    CONSTRAINT ck_entrada_pesagem_bruto CHECK (peso_bruto_kg > 0),
    CONSTRAINT ck_entrada_pesagem_tara CHECK (peso_tara_kg >= 0),
    CONSTRAINT ck_entrada_pesagem_tara_bruto
        CHECK (peso_bruto_kg > peso_tara_kg),
    CONSTRAINT ck_entrada_pesagem_liquido CHECK (peso_liquido_kg > 0),
    CONSTRAINT ck_entrada_pesagem_calculo
        CHECK (
            abs(peso_liquido_kg - (peso_bruto_kg - peso_tara_kg)) <= 0.001
        ),
    CONSTRAINT ck_entrada_pesagem_origem
        CHECK (origem IN ('BALANCA', 'MANUAL')),
    CONSTRAINT ck_entrada_pesagem_status
        CHECK (status_pesagem IN ('VALIDA', 'CANCELADA', 'ESTORNADA'))
);

COMMENT ON TABLE homologacao.entrada_produto_pesagem IS
    'Cada leitura do item. Historico preservado sem exclusao em cascata.';

CREATE UNIQUE INDEX uq_entrada_pesagem_item_sequencia
    ON homologacao.entrada_produto_pesagem (
        codigo_entrada_produto_item, sequencia
    )
    WHERE situacao_entrada_produto_pesagem = true;
CREATE INDEX ix_entrada_pesagem_item_data
    ON homologacao.entrada_produto_pesagem (
        codigo_entrada_produto_item, pesado_em DESC
    )
    WHERE situacao_entrada_produto_pesagem = true;

DO $$
DECLARE
    v_tabela text;
BEGIN
    FOREACH v_tabela IN ARRAY ARRAY[
        'entrada_produto_lancamento',
        'entrada_produto_item',
        'entrada_produto_pesagem'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_%I_atualizado_em
             BEFORE UPDATE ON homologacao.%I
             FOR EACH ROW
             EXECUTE FUNCTION homologacao.fn_definir_atualizado_em()',
            v_tabela, v_tabela
        );
        EXECUTE format(
            'CREATE TRIGGER trg_%I_log_alteracao_cadastral
             AFTER INSERT OR UPDATE OR DELETE ON homologacao.%I
             FOR EACH ROW
             EXECUTE FUNCTION homologacao.fn_registrar_log_alteracao_cadastral()',
            v_tabela, v_tabela
        );
    END LOOP;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE connamespace = 'homologacao'::regnamespace
           AND confdeltype = 'c'
           AND conrelid IN (
               'homologacao.entrada_produto_lancamento'::regclass,
               'homologacao.entrada_produto_item'::regclass,
               'homologacao.entrada_produto_pesagem'::regclass
           )
    ) THEN
        RAISE EXCEPTION 'H7 invalido: encontrada FK com ON DELETE CASCADE.';
    END IF;
END $$;

COMMIT;

-- Rollback somente com autorizacao do Gaia e sem dados historicos:
-- DROP TABLE na ordem pesagem -> item -> lancamento.
