-- ============================================================================
-- FugaPET_HML - H13 - INCREMENTAL APROVADO PELO GAIA DADOS
-- OUTBOX E REPROCESSAMENTO CONTROLADO DA INTEGRACAO SAP
-- APROVADO COMO ESTRUTURA PREPARATORIA.
-- NAO EXECUTAR AUTOMATICAMENTE. APLICACAO SOMENTE PELO USUARIO/GAIA.
-- Alvo: fuga_jales_local_homologacao_v1_2 / schema homologacao.
--
-- ESCOPO DESTE ARQUIVO:
--   - criar somente as estruturas persistentes de outbox e tentativas;
--   - nao criar, ativar ou agendar worker;
--   - nao reativar PATCH/escrita SAP;
--   - nao alterar o baseline consolidado;
--   - nao armazenar credenciais, headers, cookies, tokens ou payload bruto.
--
-- RESSALVA OBRIGATORIA DO GAIA:
--   este incremental nao torna a integracao confiavel sem implementacao C#.
--   A futura aplicacao deve gravar lancamento, itens, pesagens e outbox PENDENTE
--   na mesma transacao. Se a outbox falhar, a finalizacao local deve falhar.
-- ============================================================================

BEGIN;
SET LOCAL search_path TO homologacao, public;

DO $$
DECLARE
    v_existentes text[];
BEGIN
    SELECT array_agg(table_name ORDER BY table_name)
      INTO v_existentes
      FROM information_schema.tables
     WHERE table_schema = 'homologacao'
       AND table_name IN (
           'integracao_sap_outbox',
           'integracao_sap_tentativa'
       );

    IF COALESCE(array_length(v_existentes, 1), 0) > 0 THEN
        RAISE EXCEPTION
            'H13 nao aplicado: objetos ja existentes: %.',
            array_to_string(v_existentes, ', ');
    END IF;
END $$;

CREATE TABLE homologacao.integracao_sap_outbox (
    codigo_outbox bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_operacao varchar(50) NOT NULL,
    entidade varchar(80) NOT NULL,
    chave_negocio varchar(200) NOT NULL,
    payload_controlado jsonb NOT NULL DEFAULT '{}'::jsonb,
    situacao varchar(30) NOT NULL DEFAULT 'PENDENTE',
    tentativas integer NOT NULL DEFAULT 0,
    proxima_tentativa_em timestamptz NOT NULL DEFAULT now(),
    criado_em timestamptz NOT NULL DEFAULT now(),
    processado_em timestamptz,
    ultima_mensagem_erro varchar(1000),
    correlation_id uuid NOT NULL,

    CONSTRAINT uq_integracao_sap_outbox_idempotencia
        UNIQUE (tipo_operacao, entidade, chave_negocio),
    CONSTRAINT uq_integracao_sap_outbox_correlation
        UNIQUE (correlation_id),
    CONSTRAINT ck_integracao_sap_outbox_tipo_operacao
        CHECK (length(trim(tipo_operacao)) BETWEEN 1 AND 50),
    CONSTRAINT ck_integracao_sap_outbox_entidade
        CHECK (length(trim(entidade)) BETWEEN 1 AND 80),
    CONSTRAINT ck_integracao_sap_outbox_chave_negocio
        CHECK (length(trim(chave_negocio)) BETWEEN 1 AND 200),
    CONSTRAINT ck_integracao_sap_outbox_payload_objeto
        CHECK (jsonb_typeof(payload_controlado) = 'object'),
    CONSTRAINT ck_integracao_sap_outbox_payload_tamanho
        CHECK (octet_length(payload_controlado::text) <= 16384),
    CONSTRAINT ck_integracao_sap_outbox_payload_sem_segredos
        CHECK (
            NOT (
                payload_controlado ?| ARRAY[
                    'authorization',
                    'password',
                    'senha',
                    'token',
                    'access_token',
                    'refresh_token',
                    'cookie',
                    'set-cookie',
                    'headers',
                    'credential',
                    'credentials'
                ]
            )
        ),
    CONSTRAINT ck_integracao_sap_outbox_situacao
        CHECK (situacao IN (
            'PENDENTE',
            'PROCESSANDO',
            'PROCESSADO',
            'ERRO_REPROCESSAVEL',
            'ERRO_DEFINITIVO',
            'CANCELADO'
        )),
    CONSTRAINT ck_integracao_sap_outbox_tentativas
        CHECK (tentativas >= 0),
    CONSTRAINT ck_integracao_sap_outbox_processado
        CHECK (
            (situacao = 'PROCESSADO' AND processado_em IS NOT NULL)
            OR
            (situacao <> 'PROCESSADO' AND processado_em IS NULL)
        ),
    CONSTRAINT ck_integracao_sap_outbox_agendamento
        CHECK (
            (
                situacao IN ('PENDENTE', 'ERRO_REPROCESSAVEL')
                AND proxima_tentativa_em IS NOT NULL
            )
            OR
            (
                situacao IN (
                    'PROCESSANDO',
                    'PROCESSADO',
                    'ERRO_DEFINITIVO',
                    'CANCELADO'
                )
                AND proxima_tentativa_em IS NULL
            )
        ),
    CONSTRAINT ck_integracao_sap_outbox_erro
        CHECK (
            situacao NOT IN ('ERRO_REPROCESSAVEL', 'ERRO_DEFINITIVO')
            OR length(trim(COALESCE(ultima_mensagem_erro, ''))) > 0
        )
);

COMMENT ON TABLE homologacao.integracao_sap_outbox IS
    'Fila transacional para operacoes SAP futuras. A pendencia deve ser criada na mesma transacao da finalizacao local. Nenhum worker e ativado por este incremental.';

COMMENT ON COLUMN homologacao.integracao_sap_outbox.payload_controlado IS
    'JSON minimo e versionado, montado por allowlist. Proibido armazenar credenciais, headers, cookies, tokens, payload SAP bruto ou dados desnecessarios.';

COMMENT ON CONSTRAINT uq_integracao_sap_outbox_idempotencia
    ON homologacao.integracao_sap_outbox IS
    'Impede mais de uma pendencia para a mesma operacao e evento imutavel de negocio.';

CREATE INDEX ix_integracao_sap_outbox_processamento
    ON homologacao.integracao_sap_outbox (
        situacao,
        proxima_tentativa_em,
        codigo_outbox
    )
    WHERE situacao IN ('PENDENTE', 'ERRO_REPROCESSAVEL');

CREATE INDEX ix_integracao_sap_outbox_entidade_chave
    ON homologacao.integracao_sap_outbox (
        entidade,
        chave_negocio,
        criado_em DESC
    );

CREATE TABLE homologacao.integracao_sap_tentativa (
    codigo_tentativa bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_outbox bigint NOT NULL
        REFERENCES homologacao.integracao_sap_outbox(codigo_outbox)
        ON DELETE RESTRICT,
    numero_tentativa integer NOT NULL,
    status_http integer,
    duracao_ms bigint NOT NULL DEFAULT 0,
    mensagem_tecnica_sanitizada varchar(1000),
    executado_em timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_integracao_sap_tentativa_numero
        UNIQUE (codigo_outbox, numero_tentativa),
    CONSTRAINT ck_integracao_sap_tentativa_numero
        CHECK (numero_tentativa >= 1),
    CONSTRAINT ck_integracao_sap_tentativa_status_http
        CHECK (status_http IS NULL OR status_http BETWEEN 100 AND 599),
    CONSTRAINT ck_integracao_sap_tentativa_duracao
        CHECK (duracao_ms >= 0),
    CONSTRAINT ck_integracao_sap_tentativa_mensagem
        CHECK (
            mensagem_tecnica_sanitizada IS NULL
            OR length(mensagem_tecnica_sanitizada) <= 1000
        )
);

COMMENT ON TABLE homologacao.integracao_sap_tentativa IS
    'Historico imutavel das tentativas de processamento da outbox SAP. Nao armazena request/response bruto.';

COMMENT ON COLUMN homologacao.integracao_sap_tentativa.mensagem_tecnica_sanitizada IS
    'Mensagem tecnica limitada e sanitizada. Proibido armazenar stack trace, credenciais, headers, cookies, tokens ou resposta completa.';

CREATE INDEX ix_integracao_sap_tentativa_outbox_data
    ON homologacao.integracao_sap_tentativa (
        codigo_outbox,
        executado_em DESC
    );

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE connamespace = 'homologacao'::regnamespace
           AND conrelid = 'homologacao.integracao_sap_tentativa'::regclass
           AND contype = 'f'
           AND confdeltype = 'c'
    ) THEN
        RAISE EXCEPTION
            'H13 invalido: encontrada FK com exclusao referencial em cascata.';
    END IF;
END $$;

COMMIT;

-- ============================================================================
-- REFERENCIA PARA IMPLEMENTACAO FUTURA - NAO EXECUTADA POR ESTE SCRIPT
-- ============================================================================
--
-- 1. A finalizacao local deve inserir a outbox NA MESMA TRANSACAO que grava
--    entrada_produto_lancamento/itens/pesagens.
--
-- 2. A chave de negocio deve identificar um evento imutavel. Exemplo:
--      tipo_operacao = 'ATUALIZAR_PESO_ENTRADA'
--      entidade      = 'ENTRADA_PRODUTO_LANCAMENTO'
--      chave_negocio = 'lancamento:<codigo>:finalizacao'
--
-- 3. O futuro worker deve obter lotes com FOR UPDATE SKIP LOCKED, trocar a
--    situacao para PROCESSANDO e confirmar a transacao antes da chamada externa.
--
-- 4. Cada execucao cria uma linha em integracao_sap_tentativa. Reprocessamento
--    reutiliza o mesmo codigo_outbox e incrementa numero_tentativa/tentativas.
--
-- 5. INSERT concorrente da mesma chave deve tratar SQLSTATE 23505 como
--    idempotencia atendida, nunca criar uma segunda pendencia.
--
-- 6. PATCH/escrita SAP permanece desativado. Este incremental nao cria worker,
--    job, trigger de envio, funcao de rede ou agendamento.
--
-- Rollback somente com autorizacao do Gaia e sem historico:
-- DROP TABLE na ordem tentativa -> outbox.
