\set ON_ERROR_STOP on
-- ============================================================
-- 037_semi_acabado_HML_PROPOSTA_GAIA.sql
-- Projeto FugaPET_HML | Schema: homologacao
-- Objeto: Produto Semiacabado - persistencia local, rastreabilidade SAP 101 e etiqueta por pesagem
--
-- EXECUCAO CONTROLADA. NAO EXECUTAR AUTOMATICAMENTE.
-- Aplicar somente no DEV, apos PREFLIGHT OK.
-- Transacional, sem alteracao de dados reais e sem PRD/HML.
-- ============================================================

SET search_path TO homologacao;

BEGIN;

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '2min';

-- ============================================================
-- 1. TABELA semi_acabado_lancamento
-- ============================================================
CREATE TABLE IF NOT EXISTS homologacao.semi_acabado_lancamento
(
    codigo_semi_acabado_lancamento  bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_ordem                    varchar(40)   NOT NULL,
    material_produzido              varchar(80)   NOT NULL,
    descricao_material              varchar(255)  NOT NULL DEFAULT '',
    centro                          varchar(20)   NOT NULL DEFAULT '',
    deposito_destino                varchar(20)   NOT NULL DEFAULT '',
    item_ordem                      varchar(20)   NOT NULL DEFAULT '',
    lote                            varchar(40)   NOT NULL DEFAULT '',
    unidade                         varchar(10)   NOT NULL DEFAULT 'KG',
    quantidade_planejada_kg         numeric(14,3) NOT NULL DEFAULT 0,
    quantidade_entregue_kg          numeric(14,3) NOT NULL DEFAULT 0,
    quantidade_pendente_kg          numeric(14,3) NOT NULL DEFAULT 0,
    peso_liquido_total_kg           numeric(14,3) NOT NULL DEFAULT 0,
    status_lancamento               varchar(20)   NOT NULL DEFAULT 'FINALIZADO_LOCAL',
    material_document               varchar(20),
    material_document_year          varchar(4),
    mensagem_erro_sap               text,
    payload_preview_json            text          NOT NULL DEFAULT '',
    usuario_operacao                varchar(80)   NOT NULL DEFAULT '',
    enviado_sap_em                  timestamptz,
    criado_em                       timestamptz   NOT NULL DEFAULT now(),
    atualizado_em                   timestamptz   NOT NULL DEFAULT now()
);

COMMENT ON TABLE homologacao.semi_acabado_lancamento IS 'FugaPET incremental 037 semi_acabado';

DO $$
BEGIN
    IF obj_description('homologacao.semi_acabado_lancamento'::regclass, 'pg_class') IS DISTINCT FROM 'FugaPET incremental 037 semi_acabado' THEN
        RAISE EXCEPTION 'APLICACAO 037 ABORTADA: semi_acabado_lancamento existe sem comentario de propriedade esperado.';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'ck_semi_acabado_lancamento_status'
           AND conrelid = 'homologacao.semi_acabado_lancamento'::regclass
    ) THEN
        ALTER TABLE homologacao.semi_acabado_lancamento
            ADD CONSTRAINT ck_semi_acabado_lancamento_status
            CHECK (status_lancamento IN ('FINALIZADO_LOCAL','ENVIANDO_SAP','CONFIRMADO_SAP','ERRO_SAP','DIVERGENCIA_SAP'));
        COMMENT ON CONSTRAINT ck_semi_acabado_lancamento_status ON homologacao.semi_acabado_lancamento
            IS 'FugaPET incremental 037 semi_acabado';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'ck_semi_acabado_lancamento_documento_confirmado'
           AND conrelid = 'homologacao.semi_acabado_lancamento'::regclass
    ) THEN
        ALTER TABLE homologacao.semi_acabado_lancamento
            ADD CONSTRAINT ck_semi_acabado_lancamento_documento_confirmado
            CHECK (
                status_lancamento <> 'CONFIRMADO_SAP'
                OR (material_document IS NOT NULL AND material_document_year IS NOT NULL)
            );
        COMMENT ON CONSTRAINT ck_semi_acabado_lancamento_documento_confirmado ON homologacao.semi_acabado_lancamento
            IS 'FugaPET incremental 037 semi_acabado';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'ck_semi_acabado_lancamento_pesos_nao_negativos'
           AND conrelid = 'homologacao.semi_acabado_lancamento'::regclass
    ) THEN
        ALTER TABLE homologacao.semi_acabado_lancamento
            ADD CONSTRAINT ck_semi_acabado_lancamento_pesos_nao_negativos
            CHECK (
                quantidade_planejada_kg >= 0
                AND quantidade_entregue_kg >= 0
                AND quantidade_pendente_kg >= 0
                AND peso_liquido_total_kg >= 0
            );
        COMMENT ON CONSTRAINT ck_semi_acabado_lancamento_pesos_nao_negativos ON homologacao.semi_acabado_lancamento
            IS 'FugaPET incremental 037 semi_acabado';
    END IF;
END $$;

-- Indices de consulta e idempotencia.
CREATE INDEX IF NOT EXISTS ix_semi_acabado_lancamento_ordem_item
    ON homologacao.semi_acabado_lancamento (numero_ordem, item_ordem);
COMMENT ON INDEX homologacao.ix_semi_acabado_lancamento_ordem_item IS 'FugaPET incremental 037 semi_acabado';

CREATE INDEX IF NOT EXISTS ix_semi_acabado_lancamento_status
    ON homologacao.semi_acabado_lancamento (status_lancamento);
COMMENT ON INDEX homologacao.ix_semi_acabado_lancamento_status IS 'FugaPET incremental 037 semi_acabado';

CREATE UNIQUE INDEX IF NOT EXISTS uq_semi_acabado_lancamento_material_document
    ON homologacao.semi_acabado_lancamento (material_document, material_document_year)
    WHERE material_document IS NOT NULL AND material_document_year IS NOT NULL;
COMMENT ON INDEX homologacao.uq_semi_acabado_lancamento_material_document IS 'FugaPET incremental 037 semi_acabado';

CREATE UNIQUE INDEX IF NOT EXISTS uq_semi_acabado_lancamento_aberto_por_op_item
    ON homologacao.semi_acabado_lancamento (numero_ordem, item_ordem)
    WHERE status_lancamento IN ('FINALIZADO_LOCAL','ENVIANDO_SAP','ERRO_SAP','DIVERGENCIA_SAP');
COMMENT ON INDEX homologacao.uq_semi_acabado_lancamento_aberto_por_op_item IS 'FugaPET incremental 037 semi_acabado';

-- ============================================================
-- 2. TABELA semi_acabado_pesagem
-- ============================================================
CREATE TABLE IF NOT EXISTS homologacao.semi_acabado_pesagem
(
    codigo_semi_acabado_pesagem     bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_semi_acabado_lancamento  bigint        NOT NULL
        REFERENCES homologacao.semi_acabado_lancamento (codigo_semi_acabado_lancamento) ON DELETE RESTRICT,
    sequencia                       integer       NOT NULL,
    codigo_etiqueta                 varchar(60)   NOT NULL,
    status_pesagem                  varchar(20)   NOT NULL DEFAULT 'VALIDA',
    peso_bruto_kg                   numeric(14,3) NOT NULL,
    peso_tara_kg                    numeric(14,3) NOT NULL DEFAULT 0,
    peso_liquido_kg                 numeric(14,3) NOT NULL,
    saldo_apos_pesagem_kg           numeric(14,3) NOT NULL,
    origem                          varchar(20)   NOT NULL DEFAULT 'MANUAL',
    leitura_original                varchar(120)  NOT NULL DEFAULT '',
    codigo_tara                     bigint,
    registrado_em                   timestamptz   NOT NULL DEFAULT now(),
    cancelado_em                    timestamptz
);

COMMENT ON TABLE homologacao.semi_acabado_pesagem IS 'FugaPET incremental 037 semi_acabado';

DO $$
BEGIN
    IF obj_description('homologacao.semi_acabado_pesagem'::regclass, 'pg_class') IS DISTINCT FROM 'FugaPET incremental 037 semi_acabado' THEN
        RAISE EXCEPTION 'APLICACAO 037 ABORTADA: semi_acabado_pesagem existe sem comentario de propriedade esperado.';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'ck_semi_acabado_pesagem_status'
           AND conrelid = 'homologacao.semi_acabado_pesagem'::regclass
    ) THEN
        ALTER TABLE homologacao.semi_acabado_pesagem
            ADD CONSTRAINT ck_semi_acabado_pesagem_status
            CHECK (status_pesagem IN ('VALIDA','CANCELADA'));
        COMMENT ON CONSTRAINT ck_semi_acabado_pesagem_status ON homologacao.semi_acabado_pesagem
            IS 'FugaPET incremental 037 semi_acabado';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'ck_semi_acabado_pesagem_sequencia_positiva'
           AND conrelid = 'homologacao.semi_acabado_pesagem'::regclass
    ) THEN
        ALTER TABLE homologacao.semi_acabado_pesagem
            ADD CONSTRAINT ck_semi_acabado_pesagem_sequencia_positiva
            CHECK (sequencia > 0);
        COMMENT ON CONSTRAINT ck_semi_acabado_pesagem_sequencia_positiva ON homologacao.semi_acabado_pesagem
            IS 'FugaPET incremental 037 semi_acabado';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'ck_semi_acabado_pesagem_origem'
           AND conrelid = 'homologacao.semi_acabado_pesagem'::regclass
    ) THEN
        ALTER TABLE homologacao.semi_acabado_pesagem
            ADD CONSTRAINT ck_semi_acabado_pesagem_origem
            CHECK (origem IN ('MANUAL','BALANCA'));
        COMMENT ON CONSTRAINT ck_semi_acabado_pesagem_origem ON homologacao.semi_acabado_pesagem
            IS 'FugaPET incremental 037 semi_acabado';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'ck_semi_acabado_pesagem_pesos_nao_negativos'
           AND conrelid = 'homologacao.semi_acabado_pesagem'::regclass
    ) THEN
        ALTER TABLE homologacao.semi_acabado_pesagem
            ADD CONSTRAINT ck_semi_acabado_pesagem_pesos_nao_negativos
            CHECK (
                peso_bruto_kg >= 0
                AND peso_tara_kg >= 0
                AND peso_liquido_kg >= 0
                AND saldo_apos_pesagem_kg >= 0
            );
        COMMENT ON CONSTRAINT ck_semi_acabado_pesagem_pesos_nao_negativos ON homologacao.semi_acabado_pesagem
            IS 'FugaPET incremental 037 semi_acabado';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'ck_semi_acabado_pesagem_liquido_valida_positivo'
           AND conrelid = 'homologacao.semi_acabado_pesagem'::regclass
    ) THEN
        ALTER TABLE homologacao.semi_acabado_pesagem
            ADD CONSTRAINT ck_semi_acabado_pesagem_liquido_valida_positivo
            CHECK (status_pesagem <> 'VALIDA' OR peso_liquido_kg > 0);
        COMMENT ON CONSTRAINT ck_semi_acabado_pesagem_liquido_valida_positivo ON homologacao.semi_acabado_pesagem
            IS 'FugaPET incremental 037 semi_acabado';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'ck_semi_acabado_pesagem_cancelado_em'
           AND conrelid = 'homologacao.semi_acabado_pesagem'::regclass
    ) THEN
        ALTER TABLE homologacao.semi_acabado_pesagem
            ADD CONSTRAINT ck_semi_acabado_pesagem_cancelado_em
            CHECK (
                (status_pesagem = 'CANCELADA' AND cancelado_em IS NOT NULL)
                OR
                (status_pesagem = 'VALIDA' AND cancelado_em IS NULL)
            );
        COMMENT ON CONSTRAINT ck_semi_acabado_pesagem_cancelado_em ON homologacao.semi_acabado_pesagem
            IS 'FugaPET incremental 037 semi_acabado';
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_semi_acabado_pesagem_lancamento_sequencia
    ON homologacao.semi_acabado_pesagem (codigo_semi_acabado_lancamento, sequencia);
COMMENT ON INDEX homologacao.uq_semi_acabado_pesagem_lancamento_sequencia IS 'FugaPET incremental 037 semi_acabado';

CREATE UNIQUE INDEX IF NOT EXISTS uq_semi_acabado_pesagem_codigo_etiqueta
    ON homologacao.semi_acabado_pesagem (codigo_etiqueta);
COMMENT ON INDEX homologacao.uq_semi_acabado_pesagem_codigo_etiqueta IS 'FugaPET incremental 037 semi_acabado';

CREATE INDEX IF NOT EXISTS ix_semi_acabado_pesagem_lancamento_status
    ON homologacao.semi_acabado_pesagem (codigo_semi_acabado_lancamento, status_pesagem);
COMMENT ON INDEX homologacao.ix_semi_acabado_pesagem_lancamento_status IS 'FugaPET incremental 037 semi_acabado';

-- ============================================================
-- 3. PERMISSOES DO APP HML
-- ============================================================
DO $$
BEGIN
    RAISE NOTICE 'Papel de aplicacao HML nao identificado nos incrementais existentes. Grants especificos nao foram gerados para evitar role ficticia.';
END $$;

COMMIT;

DO $$
BEGIN
    RAISE NOTICE 'OK - APLICACAO 037 HML concluida';
END $$;
