//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FugaPET_HML.Properties
{
    using System;

    internal class Resources
    {
        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        internal Resources()
        {
        }

        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                resourceMan ??= new System.Resources.ResourceManager("FugaPET_HML.Propriedades.Resources", typeof(Resources).Assembly);
                return resourceMan;
            }
        }

        internal static System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static System.Drawing.Bitmap search_red
        {
            get
            {
                object obj = ResourceManager.GetObject("search_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap read_weight
        {
            get
            {
                object obj = ResourceManager.GetObject("read_weight", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap manual_lot
        {
            get
            {
                object obj = ResourceManager.GetObject("manual_lot", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap delete_last
        {
            get
            {
                object obj = ResourceManager.GetObject("delete_last", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap delete_code
        {
            get
            {
                object obj = ResourceManager.GetObject("delete_code", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap start_action
        {
            get
            {
                object obj = ResourceManager.GetObject("start_action", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap stop_action
        {
            get
            {
                object obj = ResourceManager.GetObject("stop_action", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap fuga_2026_logo
        {
            get
            {
                object obj = ResourceManager.GetObject("fuga_2026_logo", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap print_green
        {
            get
            {
                object obj = ResourceManager.GetObject("print_green", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap clipboard_red
        {
            get
            {
                object obj = ResourceManager.GetObject("clipboard_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap clipboard_white
        {
            get
            {
                object obj = ResourceManager.GetObject("clipboard_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap clipboard_black
        {
            get
            {
                object obj = ResourceManager.GetObject("clipboard_black", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap production_title_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("production_title_icon", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap date_card_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("date_card_icon", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap planned_production_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("planned_production_icon", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap material_card_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("material_card_icon", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap production_readings_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("production_readings_icon", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap filter_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("filter_icon", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap limpar_16x
        {
            get
            {
                object obj = ResourceManager.GetObject("limpar_16x", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap pesquisar_16x_white
        {
            get
            {
                object obj = ResourceManager.GetObject("pesquisar_16x_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap box_red
        {
            get
            {
                object obj = ResourceManager.GetObject("box_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap gear_red
        {
            get
            {
                object obj = ResourceManager.GetObject("gear_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap estatisticas_red
        {
            get
            {
                object obj = ResourceManager.GetObject("estatisticas_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap estatisticas_24_white
        {
            get
            {
                object obj = ResourceManager.GetObject("estatisticas_24_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap estatisticas_24
        {
            get
            {
                object obj = ResourceManager.GetObject("estatisticas_24", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap carga_de_trabalho_32x_red
        {
            get
            {
                object obj = ResourceManager.GetObject("carga_de_trabalho_32x_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap carga_de_trabalho_24x_white
        {
            get
            {
                object obj = ResourceManager.GetObject("carga_de_trabalho_24x_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap carga_de_trabalho_24x
        {
            get
            {
                object obj = ResourceManager.GetObject("carga_de_trabalho_24x", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap usuario_header_24_white
        {
            get
            {
                object obj = ResourceManager.GetObject("usuario_header_24_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap usuario_header_32_red
        {
            get
            {
                object obj = ResourceManager.GetObject("usuario_header_32_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap novo_usuario_32x_red
        {
            get
            {
                object obj = ResourceManager.GetObject("novo_usuario_32x_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap tara_32x_red
        {
            get
            {
                object obj = ResourceManager.GetObject("tara_32x_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap perfil_header_24_white
        {
            get
            {
                object obj = ResourceManager.GetObject("perfil_header_24_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap tara_24x_white
        {
            get
            {
                object obj = ResourceManager.GetObject("tara_24x_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap balanca_24x_white
        {
            get
            {
                object obj = ResourceManager.GetObject("balanca_24x_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap etiqueta_24x_white
        {
            get
            {
                object obj = ResourceManager.GetObject("etiqueta_24x_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap seguranca_32x_white
        {
            get
            {
                object obj = ResourceManager.GetObject("seguranca_32x_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap seguranca_24x_white
        {
            get
            {
                object obj = ResourceManager.GetObject("seguranca_24x_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap etiqueta_32x_red
        {
            get
            {
                object obj = ResourceManager.GetObject("etiqueta_32x_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap balanca_32x_red
        {
            get
            {
                object obj = ResourceManager.GetObject("balanca_32x_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap perfil_header_32_red
        {
            get
            {
                object obj = ResourceManager.GetObject("perfil_header_32_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap perfilacesso_32x_red
        {
            get
            {
                object obj = ResourceManager.GetObject("perfilacesso_32x_red", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap ordem_producao_24x_white
        {
            get
            {
                object obj = ResourceManager.GetObject("ordem_producao_24x_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap historico_menu_24x_white
        {
            get
            {
                object obj = ResourceManager.GetObject("historico_menu_24x_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        internal static System.Drawing.Bitmap sap_menu_24x_white
        {
            get
            {
                object obj = ResourceManager.GetObject("sap_menu_24x_white", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }
    }
}
